# Generated by Django 3.2.14 on 2022-08-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
